(() => {
  'use strict';
  const DEFAULTS={enabled:true,autoSelect:true,showNames:true,showPanel:true,defaultMode:'individual',panelPosition:null};
  let settings={...DEFAULTS}; let observer=null;
  const $=(s,r=document)=>r.querySelector(s);
  const $$=(s,r=document)=>[...r.querySelectorAll(s)];
  const visible=e=>{if(!e.offsetParent&&getComputedStyle(e).position!=='fixed')return false;const r=e.getBoundingClientRect();return r.width>0&&r.height>0};
  const click=e=>{if(!e)return;['mousedown','mouseup','click'].forEach(t=>e.dispatchEvent(new MouseEvent(t,{bubbles:true,cancelable:true,view:window,ctrlKey:true,metaKey:true})))};
  const selected=c=>c.classList.contains('selected')||c.classList.contains('is-selected')||c.getAttribute('aria-selected')==='true'||!!$('input[type="checkbox"]:checked',c);
  const select=c=>{const x=$('input[type="checkbox"]',c);if(x){if(!x.checked)click(x);return}click($('.photos-files_img-cover-inner',c)||$('img[data-fileid]',c))};
  const deselect=c=>{const x=$('input[type="checkbox"]',c);if(x){if(x.checked)click(x);return}click($('.photos-files_img-cover-inner',c)||$('img[data-fileid]',c))};
  const clearMarks=()=>$$('[data-gsc-marked]').forEach(e=>{e.style.outline='';e.removeAttribute('data-gsc-marked')});
  function clearSelection(){clearMarks();let n=0;$$('.file-sorter_box_thumb').forEach(c=>{if(visible(c)&&selected(c)){deselect(c);n++}});return n}
  function scan(mode){clearMarks();const seen=new Set(),names=[],color=mode==='team'?'3px solid #2563eb':'3px solid #ef4444';$$('.file-sorter_box_thumb').forEach(c=>{if(!visible(c))return;const clip=$('button[title="Clip"]',c);if(!clip||!clip.classList.contains('bg-green'))return;const indi=!!$('span[title="With Order"] .fa-shopping-cart',c),team=!!$('span[title="Tagged"] .fa-object-group',c);if(mode==='team'?!team||indi:!indi||team)return;const inner=$('.photos-files_img-cover-inner',c),img=$('img[data-fileid]',c),key=(inner&&inner.getAttribute('title'))||(img&&img.getAttribute('data-fileid'));if(!key||seen.has(key))return;seen.add(key);names.push(key);c.style.outline=color;c.setAttribute('data-gsc-marked','1');if(settings.autoSelect)select(c)});return{count:names.length,names}}
  const escapeHtml=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  function removePanel(){clearMarks();const p=$('#gsc-panel');if(p)p.remove()}
  function addStyle(){if($('#gsc-style'))return;const s=document.createElement('style');s.id='gsc-style';s.textContent=`#gsc-panel{position:fixed;top:16px;right:16px;z-index:999999;width:332px;background:#fff;border:1px solid #eee7d5;border-radius:18px;box-shadow:0 18px 55px rgba(53,44,9,.16),0 3px 12px rgba(0,0,0,.07);font:12px Inter,system-ui,sans-serif;overflow:hidden;color:#2f2a1e}#gsc-panel *{box-sizing:border-box}#gsc-header{display:flex;align-items:center;justify-content:space-between;padding:15px 16px;background:linear-gradient(135deg,#ffe36a,#f3c12d 55%,#e6b11a);cursor:grab}#gsc-title{font-weight:800;font-size:15px}#gsc-sub{display:block;font-size:9px;opacity:.65;letter-spacing:.8px;margin-top:2px;text-transform:uppercase}#gsc-collapse{border:0;background:rgba(61,48,4,.13);width:28px;height:28px;border-radius:8px;cursor:pointer;font-size:16px}#gsc-body{padding:15px}.gsc-note{margin-bottom:10px;padding:7px 9px;border:1px solid #ece4c5;background:#fffaf0;border-radius:9px;color:#876c0d;font-weight:700;text-align:center;font-size:10px}.gsc-btn{width:100%;padding:11px 13px;margin:0 0 8px;border:0;border-radius:10px;cursor:pointer;font-weight:800}.gsc-ind{background:linear-gradient(135deg,#ffe36a,#eeb80d);color:#4a3b06}.gsc-team{background:linear-gradient(135deg,#6bb1ff,#2563eb);color:#fff}.gsc-clear{background:#fff;border:1px solid #ecd6d6;color:#b42323}.gsc-status{text-align:center;color:#817968;font-size:10.5px;min-height:16px}.gsc-results{display:none;margin-top:12px;padding-top:12px;border-top:1px solid #f0ede6}.gsc-count{display:flex;justify-content:space-between;padding:10px 12px;border-radius:10px;background:#fff7df;font-weight:900}.gsc-count.team{background:#e7efff;color:#1d3f9c}.gsc-names{max-height:210px;overflow:auto;margin-top:8px}.gsc-name{padding:7px 9px;margin:5px 0;background:#fbfaf6;border-left:3px solid #e9b409;border-radius:7px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.gsc-name.team{border-left-color:#2563eb}.gsc-hidden #gsc-names{display:none}.gsc-collapsed #gsc-body{display:none}`;document.head.appendChild(s)}
  function createPanel(){if($('#gsc-panel')||!settings.enabled||!settings.showPanel)return;addStyle();const p=document.createElement('div');p.id='gsc-panel';p.innerHTML='<div id="gsc-header"><div id="gsc-title">✂️ Meilong Scissors<span id="gsc-sub">Photo selection utility</span></div><button id="gsc-collapse">−</button></div><div id="gsc-body"><div class="gsc-note">Default scan: '+(settings.defaultMode==='team'?'Team photos':'Individual photos')+'</div><button class="gsc-btn gsc-ind" id="gsc-run">✂️ Select Individual Clipped</button><button class="gsc-btn gsc-team" id="gsc-run-team">✂️ Select Team Clipped</button><button class="gsc-btn gsc-clear" id="gsc-clear">🧹 Clear Selected</button><div class="gsc-status" id="gsc-status"></div><div class="gsc-results" id="gsc-results"><div class="gsc-count" id="gsc-count"><span>Matches</span><b id="gsc-value">0</b></div><div class="gsc-names" id="gsc-names"></div></div></div>';document.body.appendChild(p);if(settings.panelPosition){p.style.right='auto';p.style.left=Math.max(0,Math.min(innerWidth-p.offsetWidth,settings.panelPosition.left))+'px';p.style.top=Math.max(0,Math.min(innerHeight-p.offsetHeight,settings.panelPosition.top))+'px'}
    $('#gsc-collapse',p).onclick=()=>p.classList.toggle('gsc-collapsed');
    const render=(mode,r)=>{$('#gsc-count',p).classList.toggle('team',mode==='team');$('#gsc-value',p).textContent=r.count;$('#gsc-names',p).innerHTML=settings.showNames?r.names.map(n=>'<div class="gsc-name '+(mode==='team'?'team':'')+'" title="'+escapeHtml(n)+'">'+escapeHtml(n)+'</div>').join(''):'';$('#gsc-results',p).style.display='block';$('#gsc-status',p).textContent=r.count+' '+(mode==='team'?'team':'individual')+' match'+(r.count===1?'':'es')+(settings.autoSelect?' and selected.':'.')};
    $('#gsc-run',p).onclick=()=>render('individual',scan('individual'));$('#gsc-run-team',p).onclick=()=>render('team',scan('team'));$('#gsc-clear',p).onclick=()=>{$('#gsc-results',p).style.display='none';const n=clearSelection();$('#gsc-status',p).textContent=n?'Cleared '+n+' selection'+(n===1?'':'s')+'.':'Nothing selected to clear.'};
    const head=$('#gsc-header',p);let drag=false,ox=0,oy=0;head.onmousedown=e=>{if(e.target.closest('#gsc-collapse'))return;drag=true;const r=p.getBoundingClientRect();ox=e.clientX-r.left;oy=e.clientY-r.top;p.style.right='auto';p.style.left=r.left+'px';p.style.top=r.top+'px';e.preventDefault()};const move=e=>{if(!drag)return;p.style.left=Math.max(0,Math.min(innerWidth-p.offsetWidth,e.clientX-ox))+'px';p.style.top=Math.max(0,Math.min(innerHeight-p.offsetHeight,e.clientY-oy))+'px'};const up=()=>{if(!drag)return;drag=false;const r=p.getBoundingClientRect();chrome.storage.local.set({panelPosition:{left:r.left,top:r.top}})};document.addEventListener('mousemove',move);document.addEventListener('mouseup',up)}
  async function init(){settings=await chrome.storage.local.get(DEFAULTS);if(settings.enabled&&settings.showPanel)createPanel();observer=new MutationObserver(()=>{if(settings.enabled&&settings.showPanel)createPanel()});observer.observe(document.body,{childList:true,subtree:true})}
  chrome.storage.onChanged.addListener((changes,area)=>{if(area!=='local')return;for(const k in changes)settings[k]=changes[k].newValue;if(!settings.enabled||!settings.showPanel)removePanel();else{removePanel();createPanel()}});init();
})();